/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_ImageZeroJNI */

#ifndef _Included_test_ImageZeroJNI
#define _Included_test_ImageZeroJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_ImageZeroJNI
 * Method:    encodeImage
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_test_ImageZeroJNI_encodeImage
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     test_ImageZeroJNI
 * Method:    getImageSize
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_test_ImageZeroJNI_getImageSize
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     test_ImageZeroJNI
 * Method:    decodeImage
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_test_ImageZeroJNI_decodeImage
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
